// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using withdrawService.Contexts;

namespace withdrawService.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("withdrawService.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            id = 1001,
                            amount = 0.0,
                            name = "saving",
                            user = 1
                        },
                        new
                        {
                            id = 1002,
                            amount = 0.0,
                            name = "checking",
                            user = 1
                        },
                        new
                        {
                            id = 1003,
                            amount = 0.0,
                            name = "saving",
                            user = 1
                        },
                        new
                        {
                            id = 1004,
                            amount = 0.0,
                            name = "checking",
                            user = 1
                        },
                        new
                        {
                            id = 1005,
                            amount = 0.0,
                            name = "checking",
                            user = 2
                        },
                        new
                        {
                            id = 1006,
                            amount = 0.0,
                            name = "saving",
                            user = 2
                        });
                });

            modelBuilder.Entity("withdrawService.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            id = 1,
                            _id = "5e98e708caf2bf4d70a1dc25",
                            email = "master@gmail.com",
                            firstname = "Amir",
                            lastname = "Kamara",
                            password = "demo"
                        },
                        new
                        {
                            id = 2,
                            _id = "5e98e78dcaf2bf4d70a1dc26",
                            email = "system@gmail.com",
                            firstname = "System",
                            lastname = "Admin",
                            password = "admin"
                        });
                });

            modelBuilder.Entity("withdrawService.Models.Account", b =>
                {
                    b.HasOne("withdrawService.Models.User", null)
                        .WithMany("accounts")
                        .HasForeignKey("Userid");
                });
#pragma warning restore 612, 618
        }
    }
}
